version: '3.7'

services:
  nginx:
    image: nginx
    container_name: bible
    #ports:
    # - 80:80
    volumes:
      - /home/ee/hugo/bible/public:/usr/share/nginx/html:ro
    networks:
      - net
    labels:
        - traefik.enable=true
        - traefik.nginx.port=80
        - traefik.frontend.entryPoints.http.redirect=https
        - traefik.frontend.rule=Host:www.bible.reguel.de,bible.reguel.de

networks:
  net:
    external: true
